server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          client-a:
            provider: uaa
            client-id: client-a
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/client-a"
            scope: authority-a
          client-b:
            provider: uaa
            client-id: client-b
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: authority-a
        provider:
          uaa:
#            issuer-uri: http://localhost:8090/uaa/oauth/token
            authorization-uri: http://localhost:8090/uaa/oauth/authorize
            token-uri: http://localhost:8090/uaa/oauth/token
            user-info-uri: http://localhost:8090/uaa/userinfo
            user-name-attribute: sub
            jwk-set-uri: http://localhost:8090/uaa/token_keys


service-a:
  uri: http://localhost:9000/service-a
